from utils.apriori import Apriori

data = [
    ('l1', 'l2', 'l5'),
    ('l2', 'l4'),
    ('l2', 'l3'),
    ('l1', 'l2', 'l4'),
    ('l1', 'l3'),
    ('l2', 'l3'),
    ('l1', 'l3'),
    ('l1', 'l2', 'l3', 'l5'),
    ('l1', 'l2', 'l3')
]

def display(model: Apriori, display_item_support_values = True, display_rules = True, display_final_itemset = True):
    """
    This method Displays the results generated by Apriori model.
    """
    if display_final_itemset:
        print(f"Final itemset values: ")
        print("item\t\tcount")
        for key, val in model.final_itemset.items():
            print(f"{key}\t\t{val}")
        print()


    if display_item_support_values:
        print(f"Filtered item support values: ")
        print("item\t\tcount")
        for key, val in model.item_support_values.items():
            print(f"{key}\t\t{val}")
        print()

    if display_rules:
        print(f"Rules derived from given data: ")
        print("X ->>\t\tY")
        for key, val in model.rules.items():
            print(f"{key}\t\t{val}")
        print()

if __name__ == "__main__":
    model = Apriori(min_support = 0.22, min_confidence = 0.6)
    model.fit(data)
    display(model)
    
